# Generated by Django 3.0.7 on 2020-06-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='contnt',
            new_name='content',
        ),
    ]
