# Generated by Django 3.0.7 on 2020-06-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
